[[redirects]]
  from = "/login"
  to = "/login.html"
  status = 200

[[redirects]]
  from = "/discord/profile"
  to = "/profile.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 200
